---
# Copyright 2019 tecRacer GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
AWSTemplateFormatVersion: '2010-09-09'
Description: Security for Jenkins Server with dynamic Nodes
Parameters:
  VPC:
    Description: 'Id of vpc'
    Type: String

Resources:
###
# Security Groups
  SecurityGroupJenkinsServer:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: "Jenkins Server"
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          CidrIp: 0.0.0.0/0
          FromPort: 80
          ToPort: 80

  SecurityGroupJenkinsNode:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: "Jenkins Node"
      VpcId: !Ref VPC

  SecurityJenkinsToNodes:
    Type: 'AWS::EC2::SecurityGroupIngress'
    Properties:
      GroupId: !Ref SecurityGroupJenkinsNode
      IpProtocol: tcp
      FromPort: 22
      ToPort: 22
      SourceSecurityGroupId: !Ref SecurityGroupJenkinsServer


#
###

###
# Role for Jenkins Server

  JenkinsRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - 'ec2.amazonaws.com'
          Action:
          - 'sts:AssumeRole'
      Path: '/'
      Policies:
      - PolicyName: jenkins
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - 'logs:CreateLogStream'
            - 'logs:PutLogEvents'
            - 'logs:DescribeLogStreams'
            - 'ec2:DescribeSpotInstanceRequests'
            - 'ec2:CancelSpotInstanceRequests'
            - 'ec2:GetConsoleOutput'
            - 'ec2:RequestSpotInstances'
            - 'ec2:RunInstances'
            - 'ec2:StartInstances'
            - 'ec2:StopInstances'
            - 'ec2:TerminateInstances'
            - 'ec2:CreateTags'
            - 'ec2:DeleteTags'
            - 'ec2:DescribeInstances'
            - 'ec2:DescribeKeyPairs'
            - 'ec2:DescribeRegions'
            - 'ec2:DescribeImages'
            - 'ec2:DescribeAvailabilityZones'
            - 'ec2:DescribeSecurityGroups'
            - 'ec2:DescribeSubnets'
            - 'iam:ListInstanceProfilesForRole'
            - 'iam:PassRole'
            Resource: "*"
  #
  ###